spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    password: root
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: fabian81tester@gmail.com
    password: JoyDivision80&
    properties: 
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
server:
  context-path: /flightreservation
  
logging:
  level:
    root: INFO
  file: /Users/fabiang81/Documents/reservations/logs/flightreservation.log
  
com:
  fabian81:
    flightreservation:
      itinerary:
        dirpath: /Users/fabiang81/Documents/reservations/reservation
        email:
          subject: Please find your itinerary attached
          body: Itinerary for your flight